config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#index'
  # Provide a route for :provider strategies to "call back" to
  # after the authenticating 3rd party decides whether the user has passed or failed authentication
  # handshake
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  # Handshake - when user login to github, github sends them back to my application - callback URL
    # How Github redirects user back to my app and provides app with secret code representing Github user
    # App sends secret code back to GitHuhb - Git Hub confirms code
    # GitHub sends back user's data
  get '/auth/github/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # Users
  resources :users, only: [:index, :new, :create, :show] do 
    # Sends as nested resources of a user
    resources :sends
    # Aliased path names
    get '/sends/sort/easiest', to: 'sends#easiest', as: :easiest_sends
    get '/sends/sort/hardest', to: 'sends#hardest', as: :hardest_sends
    get '/sends/sort/favorites', to: 'sends#favorites', as: :favorite_sends
    get '/sends/sort/color', to: 'sends#color', as: :selected_color_sends
  end 
  
  # Problems
  resources :problems, only: [:index, :show, :new, :create]
  get '/problems/sort/easiest', to: 'problems#easiest', as: :easiest_problems
  get '/problems/sort/hardest', to: 'problems#hardest', as: :hardest_problems
  # get '/problems/filter/style', to: 'problems#style' # maybe
  # get '/problems/filter/wall', to: 'problems#wall' # maybe
  resources :rewards, only: [:index, :show, :new, :create]
end

app/models/problem.rb
class Problem < ApplicationRecord
  belongs_to :wall
  has_many :sends
  has_many :users, through: :sends
  has_many :problem_styles
  has_many :styles, through: :problem_styles
  validates_presence_of :name, :color, :grade
  # Query Problem table for all problem instances
  scope :sort_by_date, -> { order('created_at desc') }
  scope :sort_by_grade, -> { order('grade desc') } 
  # scope :sort_by_color -> (selected_color) { where('color: selected_color') }
  
  # scope :filter_by_grades -> (min_grade, max_grade) { where(grade: (min_grade..max_grade)) }
  # scope :filter_by_style -> (selected_style) { where(style: selected_style) }
  # scope :filter_by_wall -> (selected_wall) { where(wall_id: selected_wall ) }


  # Constants for colors + grades as a single source of truth
  # If we ever need to change colors, we can do so here
  # other places it's referenced will updated as well
  COLORS = [
    "White",
    "Red",
    "Orange",
    "Yellow",
    "Green",
    "Lime",
    "Blue",
    "Pink",
    "Purple",
    "Black"
  ]

  GRADES = [
    "V0",
    "V1",
    "V2",
    "V3",
    "V4",
    "V5",
    "V6",
    "V7",
    "V8",
    "V9",
    "V10",
    "V11",
    "V12",
    "V13"
  ]

  def convert_created_at_to_date
    self.created_at.in_time_zone("Eastern Time (US & Canada)").to_date
  end
  

end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :require_login

  def index
    @problems = Problem.sort_by_date
  end
  
  def new
    @problem = Problem.new
  end

  def create
    @problem = Problem.new(problem_params)
    @problem.points = @problem.convert_grade_to_int

    if @problem.save
      redirect_to problems_path
    else
      # @problem is now full of error messages
      # re-rendered :new page knows how to display errors alongside user's enries
      render :new
    end
  end

  def show
    @problem = Problem.find_by_id(params[:id])
    if !@problem
      flash[:alert] = "Problem doesn't exit."
      redirect_to problems_path
    end
  end

  def easiest
    @problems = Problem.sort_by_grade.reverse
    render :index
  end

  def hardest
    @problems = Problem.sort_by_grade
    render :index
  end

  def grades
    @problems = Problem.filter_by_grades(min, max)
    render :index
  end

  def styles
    @problems = Problem.filter_by_style(selected_style)
    render :index
  end

  def walls
    @problems = Problem.filter_by_wall(selected_wall)
    render :index
  end
 
  private

  def problem_params
    params.require(:problem).permit(:wall_id, :name, :color, :grade, :image, style_ids:[])
  end
end

app/helpers/problems_helper.rb
# Model code isn't concerned with presentation logic
# Extract presentation logic from multiple views with helpers

module ProblemsHelper
  # Create a datetime, this method should convert it from datetime
  # 'Sun, 08 Mar 2020 21:51:37 UTC +00:00' to 'Month, year'
  # Use method in problems/index and show pages
  def format_timestamp_to_set_month(problem)
    problem.created_at.strftime("%B, %Y")
  end
  
  # Display str of styles for each problem on problems/show view
  def display_styles(problem)  
    problem.styles.map(&:name).join(', ')
  end

  def display_sends_count(problem)
   "Send".pluralize(problem.sends.count) + ": " + problem.sends.count.to_s
  end
end

app/views/problems/index.html.erb
<!-- Display all problems -->
<h1 class="heading">All Problem Logs</h1>
<%= button_to "Add New Problem", new_problem_path, method: 'get', class: 'btn btn-outline-primary btn-lg' %><br>

<h4>Sort By</h4>
<ul>
  <li><%= link_to "Most Recent (default)", problems_path %></li>
  <%# <li>Wall</li> %>
  <%# <%= select_tag :wall_id, options_from_collection_for_select(Wall.all, :id, :name), prompt: 'Select Wall' %> 
  <li><%= link_to "Easiest", easiest_problems_path %></li>
  <li><%= link_to "Hardest", hardest_problems_path %></li>
  <%# <li>Style</li>   %>
</ul>
<br><hr>

<h2>All Results</h2>
<table class="table table-bordered table-striped table-hover">
  <thead class="thead-dark">
    <th>Set</th>
    <th>Wall</th>
    <th>Name</th>
    <th>Color</th>
    <th>Grade</th>
    <th>Sends</th>
    <th>See Details</th>
  </thead>
  <tbody>
    <% @problems.each do |problem| %>
      <tr>
        <td><%= format_timestamp_to_set_month(problem) %></td>
        <td><%= problem.wall.name %></td>
        <td><h5><%= problem.name %></h5></td>
        <td><%= problem.color %></td>
        <td><%= problem.grade %></td>
        <td><%= problem.sends.count %></td>
        <td><%= button_to 'See details', problem_path(problem), method: "get", class: "btn btn-info" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/problems/new.html.erb
<h2>Create a New Problem</h2>

<%= render partial: '/errors', locals: { record: @problem } %><br>

<%= form_for @problem do |f| %>
  <%= f.label :wall %>
  <div><%= f.select :wall_id, options_from_collection_for_select(Wall.all, :id, :name), prompt: 'Select Wall' %></div>
  <br>
  <%= f.label :name %>
  <div><%= f.text_field :name %></div>
  <br>
  <%= f.label :color %>
  <!-- f.select :color, options_for_select(Problem::COLORS, :color, :color) -->
  <div><%= f.select :color, options_for_select(Problem::COLORS), prompt: 'Select Color' %></div>
  <br>
  <%= f.label :grade %>
  <div><%= f.select :grade, options_for_select(Problem::GRADES), prompt: 'Select Grade' %></div>
  <br>
  <%= f.label :styles %><br>
  <div class="checkboxes"><%= f.collection_check_boxes :style_ids, Style.all, :id, :name %></div>
  <!-- <input type="checkbox" value="1" name="problem[style_ids][]" id="style_id"> -->
  <br>
  <%= f.label :image %>
  <div><%= f.text_field :image %></div>
  <i>*Instructions: Drop your image onto <a href="https://imgur.com">Imgur</a>. Click 'get share links' and copy the "Embed in HTML" link.</i>
  <br><br>

  <%= f.submit class:"btn btn-lg btn-success" %> 
<% end %>

app/views/problems/show.html.erb
<h1 class="heading"><%= @problem.name %> at <%= @problem.wall.name %> Wall</h1>
<h3 class="subheading">Set: <%= format_timestamp_to_set_month(@problem) %></h3>
<h4><%= display_sends_count(@problem) %></a></h4>
<ul>
  <li>Color: <%= @problem.color %></li>
  <li>Grade: <%= @problem.grade %></li>
  <!-- helper method to display style in sentence -->
  <li>Styles: <%= display_styles(@problem) %></li>
  <% if @problem.image.present? %>
    <li>Image:<br><i><%= @problem.image.html_safe %></i></li>
  <% end %>
</ul>

<br><br>
<h3 class="subheading">ACTIVITY</h3><hr>
<!-- order by least attempts? or latest?-->
<% @problem.sends.each do |send| %>
  <h3 class="subheading">@<%= link_to send.user.username, user_path(send.user) %></h3>  
  <!-- float right if possible -->
  <p><%= display_attempts(send) %></p>
  <p>Sent on: <%= display_date_sent(send) %></p>
  <p><%= send.image.html_safe if send.image %></p>
  <br>
<% end %>