config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#index'
  # Provide a route for :provider strategies to "call back" to
  # after the authenticating 3rd party decides whether the user has passed or failed authentication
  # handshake
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  # Handshake - when user login to github, github sends them back to my application - callback URL
    # How Github redirects user back to my app and provides app with secret code representing Github user
    # App sends secret code back to GitHuhb - Git Hub confirms code
    # GitHub sends back user's data
  get '/auth/github/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # Users
  resources :users, only: [:index, :new, :create, :show] do 
    # Sends as nested resources of a user
    resources :sends
    # Aliased path names
    get '/sends/sort/easiest', to: 'sends#easiest', as: :easiest_sends
    get '/sends/sort/hardest', to: 'sends#hardest', as: :hardest_sends
    get '/sends/sort/favorites', to: 'sends#favorites', as: :favorite_sends
    get '/sends/sort/color', to: 'sends#color', as: :selected_color_sends
  end 
  
  # Problems
  resources :problems, only: [:index, :show, :new, :create]
  get '/problems/sort/easiest', to: 'problems#easiest', as: :easiest_problems
  get '/problems/sort/hardest', to: 'problems#hardest', as: :hardest_problems
  # get '/problems/filter/style', to: 'problems#style' # maybe
  # get '/problems/filter/wall', to: 'problems#wall' # maybe
  resources :rewards, only: [:index, :show, :new, :create]
end

app/models/send.rb
class Send < ApplicationRecord
  belongs_to :user
  belongs_to :problem

  validates_presence_of :user_id, :date_sent
  validates :problem_id, presence: { message: "must be selected" }, uniqueness: { scope: :user_id, message: "can only be sent once" }
  validates :attempts, presence: true, numericality: { greater_than: 0 }
  validate :valid_date?

  scope :sort_by_date, -> { order('date_sent desc') }
  scope :sort_by_grade_desc, -> (user) {
    where(user_id: user).joins(:problem).order('grade desc')
  }
  scope :sort_by_grade_asc, -> (user) {
    where(user_id: user).joins(:problem).order('grade asc')
  }


  scope :sort_sends_by_color, -> (id, selected_color) {
    sort_by_date.where(user_id: id).joins(:problem).where('problems.color = ?', selected_color)
  }

  # scope :filter_by_wall -> (selected_wall) { where(wall_id: selected_wall ) }
  # scope :filter_by_grades -> (min_grade, max_grade) { where(grade: (min_grade..max_grade)) }
  # scope :filter_by_style -> (selected_style) { where(style: selected_style) }

  # Custom method to verify the state of Send model
  # Validate send.date_sent > send.problem.created_at date
  def valid_date?
    if date_sent.present? && self.problem.present? && (date_sent < self.problem.convert_created_at_to_date)
      # add message to the errors collection
      errors.add(:date_sent, "must be on or after problem set date")
    end
  end
end

app/controllers/sends_controller.rb
# To handle the nested resource we set up
class SendsController < ApplicationController
  # call to the ActionController class method before_action
  # register a filter 
  before_action :require_login
  before_action :get_user, only:[:index, :show, :new, :create, :hardest, :easiest, :favorites, :color, :edit, :update]
  before_action :get_send, only:[:show, :edit, :update, :destroy]
  before_action :get_walls, only:[:new, :edit]

  before_action :validate_user
  before_action :validate_sender, only: [:new, :create, :edit, :update, :destroy]
  before_action :no_sends?, only: [:index, :show]
  before_action :validate_send_id, only: [:show, :update, :destroy]

  def index
    @sends = @user.sort_user_sends_by_date
  end
  
  def show

  end
 
  def new
    @send = Send.new
  end

  def create
    # user that I want to associate with this send
    # shielding data by assigning send's user_id here instead of via hidden_field in view form
    @send = current_user.sends.build(send_params)
 
    if @send.save #if able to run validations
      redirect_to user_send_path(@send.user, @send)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @send.update(send_params)
    if @send.save
      redirect_to user_sends_path(@send.user, @send)
    else
      render :edit
    end
  end

  def destroy
   @send.destroy
   redirect_to user_sends_path(@send.user)
  end

  def hardest
    @sends = Send.sort_by_grade_desc(@user.id)
    render :index
  end

  def easiest
    @sends = Send.sort_by_grade_asc(@user.id)
    render :index
  end

  def favorites
    @sends = @user.favorite_sends
    render :index
  end

  def color
    @sends = Send.sort_sends_by_color(@user.id, params[:color])
    render :index
  end


  private 
  def get_user
    # returns @user or find user and set the instance variable 
    @user ||= User.find_by(id: params[:user_id])
  end

  def get_send
    # returns @user or find user and set the instance variable 
    @send ||= Send.find_by(id: params[:id])
  end

  def get_walls
    @walls ||= Wall.all
  end
 
  def validate_sender
    validate_user
    if current_user != get_user
      flash[:alert] = "You're not authroized to create/ update this user's sends!"  
      redirect_to user_sends_path(get_user) 
    end
  end

  def validate_send_id
    if !get_send
      flash[:alert] = "This send doesn't exist. Please check out other sends by #{get_user.username}."  
      redirect_to user_sends_path(get_user)
    end
  end

  def no_sends?
    if @user.sends.empty?
      flash[:alert] = "@#{get_user.username} has not logged any sends yet."  
      redirect_to user_path(get_user) 
    end
  end

  def send_params
    params.require(:send).permit(:problem_id, :user_id, :attempts, :date_sent, :image, :favorite)
  end
end

app/helpers/sends_helper.rb
module SendsHelper
  def display_attempts(send)
    attempts = send.attempts
    if attempts == 1
      '⚡ Flashed'
    else
      "✅ #{attempts} attempts"
    end
  end

  def display_date_sent(send)
    send.date_sent.strftime("%A, %e %B %Y")
  end
end

app/views/sends/_form.html.erb
<%= render partial: '/errors', locals: { record: @send } %><br>

<%# form_for knows that an empty, unsaved model object needs a new form %>
 <%# and a populated object needs an edit form %>
<%= form_for(@send, url: selected_path) do |f| %>
  <% if problem_editable %>
    <h4>Which problem did you send?</h4>
    <%# option_groups_from_collection_for_select %>
    <%# Returns str of <option> tags, %> 
    <%# grouped by <optgroup> tags based on the object relationships of the arguments %>
    <%# (collection, group_method, group_label_method/ wall.name, option_key_method/ problem_id, option_value_method/ problem.name, selected_key = nil)%>
    <div><%= f.select :problem_id, option_groups_from_collection_for_select(
      @walls, :problems, :name, :id, :name, @send.problem_id || nil
    ), prompt: "Select Problem"%></div>
  <% else %>
    <h3 class="subheading"><%= @send.problem.name %> at <%= @send.problem.wall.name %> Wall</h3>
  <% end %>
  <br>
  <%= f.label :attempts %>
  <div><%= f.number_field :attempts, min: 1 %></div>
  <br>
  <%# date sent must be after problem created_at date %>
  <%= f.label :date_sent %>
  <div><%= f.date_field :date_sent, max: Date.today %></div>
  <br>
  <%= f.label :image %>
  <div><%= f.text_field :image %></div>
  <br>
  <%= f.label "Add to your favorites?" %>
  <%= f.check_box :favorite %>
  <br>
  <%= f.submit class: "btn btn-lg btn-info" %>
<% end %>

app/views/sends/edit.html.erb
<h1 class="heading"> Edit a Send</h1>
<%# url: '/users/:user_id/sends/:id', method: 'PATCH ' %> 
<%= render partial: 'form', locals: { selected_path: user_send_path, problem_editable: false} %>

app/views/sends/index.html.erb
<h1 class="heading">All of @<%= @user.username %>'s Sends</h1>
<!-- Display sent problem through partial -->
<%= (button_to "Add New Send", new_user_send_path, method: 'get', class: "btn btn-outline-primary btn-lg")  if current_user == @user %>

<%= render '/layouts/user_preview' %>
<hr>

<h4>Sort Sends By</h4>
<ul>
  <li><%= link_to "Most Recent (default)", user_sends_path(@user) %></li>
  <%# <li>Wall</li>
  <%= select_tag :wall_id, options_from_collection_for_select(Wall.all, :id, :name), prompt: 'Select Wall' %>
  <li><%= link_to "Hardest to easiest", user_hardest_sends_path(@user) %></li> 
  <li><%= link_to "Easiest to hardest", user_easiest_sends_path(@user) %></li> 
  <li><%= link_to "Favorites", user_favorite_sends_path(@user) %></li> 
  <%# Filter by color %>
  <li>
  <%= form_tag(user_selected_color_sends_path(@user), method: 'get') do %>
  <%= select_tag :color, options_for_select(Problem::COLORS), prompt: 'Filter by Color'%>
    <%= submit_tag :filter, class: "btn btn-outline-primary btn-sm" %>
  <% end %>   
  </li>
</ul>
<br><hr>

<h2> All Results </h2>
<!-- Display sends -->
<table class="table table-bordered table-striped table-hover">
  <thead class="thead-dark">
    <th>Date Sent</th>
    <th>Problem Name</th>
    <th>Wall</th>
    <th>Color</th>
    <th>Grade</th>
    <th>Attempts</th>
    <th></th> <!-- link to send -->
    <% if @user == current_user %>
      <th></th> <!-- edit send -->
      <th></th> <!-- delete send -->
    <% end %>
  </thead>
  <tbody>
    <% @sends.each do |send| %>
      <tr>
        <td><%= send.date_sent %></td>
        <td><h5><%= link_to send.problem.name, problem_path(send.problem) %></h5></td>
        <td><%= send.problem.wall.name %></td>
        <td><%= send.problem.color %></td>
        <td><%= send.problem.grade %></td>
        <td><%= display_attempts(send) %></td>
        <td><%= button_to 'See details', user_send_path(@user, send), method: "get", class: "btn btn-info" %></td>
        <% if @user == current_user %>
          <td><%= button_to "Edit send", edit_user_send_path(@user, send), method: "get", class: "btn btn-info" %></td>
          <!-- <button_to(str), URL, method:"DELETE", class:"destory"></button>`-->
          <td><%= button_to "x", user_send_path(@user, send), method: "delete", class: "btn btn-outline-danger btn-sm" %></td>
        <% end %> 
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sends/new.html.erb
<h1 class="heading">Hey <%= @user.username %>, log your send!</h1>

<%# url: '/users/:user_id/sends', method: 'POST' %>
<%= render partial: 'form', locals: { selected_path: user_sends_path , problem_editable: true} %>

app/views/sends/show.html.erb
<h1 class="heading">@<%= @send.user.username %>'s Send</h1>

<h2><%=@send.problem.name %> at <%=@send.problem.wall.name%> Wall</h2><br>
<% if @send.favorite %>
  <p class="fav">❤️ Favorited</p>
<% end %>
<p><%= display_attempts(@send) %></p>
<p>Sent on: <%= display_date_sent(@send) %></p>
<%= @send.image.html_safe if @send.image %>
<br><br>
  
 <div class="btn-group"><%= button_to "Check out this problem", problem_path(@send.problem), method: 'get', class: "btn btn-success btn-lg" %></div>
<% if @send.user == current_user %>
  <div class="btn-group"><%= button_to "Edit send", edit_user_send_path(@send.user, @send), method: 'get', class: "btn btn-primary btn-lg" %></div>
  <div class="btn-group"><%= button_to "Delete Send", user_send_path(@send.user, @send), method: "delete", class: "btn btn-danger btn-lg" %></div>
<% end %>