config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#index'
  # Provide a route for :provider strategies to "call back" to
  # after the authenticating 3rd party decides whether the user has passed or failed authentication
  # handshake
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  # Handshake - when user login to github, github sends them back to my application - callback URL
    # How Github redirects user back to my app and provides app with secret code representing Github user
    # App sends secret code back to GitHuhb - Git Hub confirms code
    # GitHub sends back user's data
  get '/auth/github/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # Users
  resources :users, only: [:index, :new, :create, :show] do 
    # Sends as nested resources of a user
    resources :sends
    # Aliased path names
    get '/sends/sort/easiest', to: 'sends#easiest', as: :easiest_sends
    get '/sends/sort/hardest', to: 'sends#hardest', as: :hardest_sends
    get '/sends/sort/favorites', to: 'sends#favorites', as: :favorite_sends
    get '/sends/sort/color', to: 'sends#color', as: :selected_color_sends
  end 
  
  # Problems
  resources :problems, only: [:index, :show, :new, :create]
  get '/problems/sort/easiest', to: 'problems#easiest', as: :easiest_problems
  get '/problems/sort/hardest', to: 'problems#hardest', as: :hardest_problems
  # get '/problems/filter/style', to: 'problems#style' # maybe
  # get '/problems/filter/wall', to: 'problems#wall' # maybe
  resources :rewards, only: [:index, :show, :new, :create]
end

app/views/layouts/_navbar.html.erb
<%# <a class="navbar-brand" href="/"><img src="/images/icon.png" alt="logo"></a> %>
<%= link_to image_tag("icon.png"), root_path, class: "navbar-brand" %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to "Homepage", root_path, class: "nav-link" %>
    </li>

    <% if logged_in? %>
      <li class="nav-item">
        <%= link_to "All Problems", problems_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "All Users", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Your Sends", user_sends_path(current_user), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "@#{current_user.username}", user_path(current_user), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Log Out", logout_path, class: "nav-link" %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "Create Account", new_user_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Login", login_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Login via GitHub", '/auth/github', class: "nav-link" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/_user_preview.html.erb
<h4>
  <%= image_tag "problems_sent.png", class: "image_icon" %>
  Problems Sent: <%= @user.sends.count %>
</h4>
<h4>
  <%= image_tag "hardest_send.png", class: "image_icon" %>
  Hardest Send: <%= @user.hardest_send || "@#{@user.username} has not logged any sends."%> 
</h4><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Bolderer</title>
    <%= favicon_link_tag asset_path('icon.png'), :rel => 'icon', :type =>  'image/png' %>


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    
    <!-- Custom CSS -->
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Navigation bar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= render 'layouts/navbar' %>
    </nav>

    <div class="container">
      <div class="wrapper">

      <% flash.each do |name, message| %>
        <% alert_class = case name
                        when 'notice' then "success"
                        when 'alert' then "danger"
                        else name
                        end %>
         <%= content_tag :div, class: "alert alert-#{alert_class}" do %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= message %>
        <% end %>
      <% end %>
      
      <%= yield %>

    </div>
  </div>

    <footer class="footer">
      <div class="container">
        <p class="text-muted">by Jacqueline K. Lam</p>
       </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

    <!--[if lt IE 7]>
      <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
      <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
    <![endif]-->
  </body>
</html>